node {
    checkout scm

    docker.withRegistry('https://registry.hub.docker.com', 'dockerHub') {

        def customImage = docker.build("hsmnzaydn/service-user")

        /* Push the container to the custom Registry */
        customImage.push()
    }
}